// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: message_proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Produce RPC messages
type ProduceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientMessageId string                 `protobuf:"bytes,1,opt,name=client_message_id,json=clientMessageId,proto3" json:"client_message_id,omitempty"` // Client-generated ID for correlation
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Key             []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Headers         []*MessageHeader       `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_message_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceRequest) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProduceRequest) GetHeaders() []*MessageHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProduceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientMessageId string                 `protobuf:"bytes,1,opt,name=client_message_id,json=clientMessageId,proto3" json:"client_message_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Populated if success is false
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_message_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceResponse) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

func (x *ProduceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProduceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Consume RPC messages
type ConsumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*ConsumeRequest_Subscribe
	//	*ConsumeRequest_Ack
	RequestType   isConsumeRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_message_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeRequest) GetRequestType() isConsumeRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *ConsumeRequest) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.RequestType.(*ConsumeRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ConsumeRequest) GetAck() *AckMessage {
	if x != nil {
		if x, ok := x.RequestType.(*ConsumeRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isConsumeRequest_RequestType interface {
	isConsumeRequest_RequestType()
}

type ConsumeRequest_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type ConsumeRequest_Ack struct {
	Ack *AckMessage `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ConsumeRequest_Subscribe) isConsumeRequest_RequestType() {}

func (*ConsumeRequest_Ack) isConsumeRequest_RequestType() {}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_message_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Server-generated ID from ConsumeResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_message_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *AckMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Server-generated unique ID for this message
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           []byte                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Headers       []*MessageHeader       `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_message_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConsumeResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ConsumeResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConsumeResponse) GetHeaders() []*MessageHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Common message header structure
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_message_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_message_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_message_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *MessageHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MessageHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_message_proxy_proto protoreflect.FileDescriptor

const file_message_proxy_proto_rawDesc = "" +
	"\n" +
	"\x13message_proxy.proto\x12\rmessage_proxy\"\xb2\x01\n" +
	"\x0eProduceRequest\x12*\n" +
	"\x11client_message_id\x18\x01 \x01(\tR\x0fclientMessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x126\n" +
	"\aheaders\x18\x05 \x03(\v2\x1c.message_proxy.MessageHeaderR\aheaders\"|\n" +
	"\x0fProduceResponse\x12*\n" +
	"\x11client_message_id\x18\x01 \x01(\tR\x0fclientMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x90\x01\n" +
	"\x0eConsumeRequest\x12?\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1f.message_proxy.SubscribeRequestH\x00R\tsubscribe\x12-\n" +
	"\x03ack\x18\x02 \x01(\v2\x19.message_proxy.AckMessageH\x00R\x03ackB\x0e\n" +
	"\frequest_type\"N\n" +
	"\x10SubscribeRequest\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"+\n" +
	"\n" +
	"AckMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xdc\x01\n" +
	"\x0fConsumeResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03key\x18\x05 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x126\n" +
	"\aheaders\x18\a \x03(\v2\x1c.message_proxy.MessageHeaderR\aheaders\"7\n" +
	"\rMessageHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\xaa\x01\n" +
	"\fMessageProxy\x12L\n" +
	"\aProduce\x12\x1d.message_proxy.ProduceRequest\x1a\x1e.message_proxy.ProduceResponse(\x010\x01\x12L\n" +
	"\aConsume\x12\x1d.message_proxy.ConsumeRequest\x1a\x1e.message_proxy.ConsumeResponse(\x010\x01B\x17Z\x15kafka-proxy/pkg/proxyb\x06proto3"

var (
	file_message_proxy_proto_rawDescOnce sync.Once
	file_message_proxy_proto_rawDescData []byte
)

func file_message_proxy_proto_rawDescGZIP() []byte {
	file_message_proxy_proto_rawDescOnce.Do(func() {
		file_message_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proxy_proto_rawDesc), len(file_message_proxy_proto_rawDesc)))
	})
	return file_message_proxy_proto_rawDescData
}

var file_message_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_proxy_proto_goTypes = []any{
	(*ProduceRequest)(nil),   // 0: message_proxy.ProduceRequest
	(*ProduceResponse)(nil),  // 1: message_proxy.ProduceResponse
	(*ConsumeRequest)(nil),   // 2: message_proxy.ConsumeRequest
	(*SubscribeRequest)(nil), // 3: message_proxy.SubscribeRequest
	(*AckMessage)(nil),       // 4: message_proxy.AckMessage
	(*ConsumeResponse)(nil),  // 5: message_proxy.ConsumeResponse
	(*MessageHeader)(nil),    // 6: message_proxy.MessageHeader
}
var file_message_proxy_proto_depIdxs = []int32{
	6, // 0: message_proxy.ProduceRequest.headers:type_name -> message_proxy.MessageHeader
	3, // 1: message_proxy.ConsumeRequest.subscribe:type_name -> message_proxy.SubscribeRequest
	4, // 2: message_proxy.ConsumeRequest.ack:type_name -> message_proxy.AckMessage
	6, // 3: message_proxy.ConsumeResponse.headers:type_name -> message_proxy.MessageHeader
	0, // 4: message_proxy.MessageProxy.Produce:input_type -> message_proxy.ProduceRequest
	2, // 5: message_proxy.MessageProxy.Consume:input_type -> message_proxy.ConsumeRequest
	1, // 6: message_proxy.MessageProxy.Produce:output_type -> message_proxy.ProduceResponse
	5, // 7: message_proxy.MessageProxy.Consume:output_type -> message_proxy.ConsumeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proxy_proto_init() }
func file_message_proxy_proto_init() {
	if File_message_proxy_proto != nil {
		return
	}
	file_message_proxy_proto_msgTypes[2].OneofWrappers = []any{
		(*ConsumeRequest_Subscribe)(nil),
		(*ConsumeRequest_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proxy_proto_rawDesc), len(file_message_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proxy_proto_goTypes,
		DependencyIndexes: file_message_proxy_proto_depIdxs,
		MessageInfos:      file_message_proxy_proto_msgTypes,
	}.Build()
	File_message_proxy_proto = out.File
	file_message_proxy_proto_goTypes = nil
	file_message_proxy_proto_depIdxs = nil
}
