// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: proto/message_proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageProxy_Produce_FullMethodName = "/message_proxy.MessageProxy/Produce"
	MessageProxy_Consume_FullMethodName = "/message_proxy.MessageProxy/Consume"
)

// MessageProxyClient is the client API for MessageProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessageProxy service definition
type MessageProxyClient interface {
	// Bi-directional streaming RPC for producing messages
	Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProduceRequest, ProduceResponse], error)
	// Bi-directional streaming RPC for consuming messages
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error)
}

type messageProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageProxyClient(cc grpc.ClientConnInterface) MessageProxyClient {
	return &messageProxyClient{cc}
}

func (c *messageProxyClient) Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProduceRequest, ProduceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageProxy_ServiceDesc.Streams[0], MessageProxy_Produce_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProduceRequest, ProduceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageProxy_ProduceClient = grpc.BidiStreamingClient[ProduceRequest, ProduceResponse]

func (c *messageProxyClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageProxy_ServiceDesc.Streams[1], MessageProxy_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageProxy_ConsumeClient = grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse]

// MessageProxyServer is the server API for MessageProxy service.
// All implementations must embed UnimplementedMessageProxyServer
// for forward compatibility.
//
// MessageProxy service definition
type MessageProxyServer interface {
	// Bi-directional streaming RPC for producing messages
	Produce(grpc.BidiStreamingServer[ProduceRequest, ProduceResponse]) error
	// Bi-directional streaming RPC for consuming messages
	Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error
	mustEmbedUnimplementedMessageProxyServer()
}

// UnimplementedMessageProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageProxyServer struct{}

func (UnimplementedMessageProxyServer) Produce(grpc.BidiStreamingServer[ProduceRequest, ProduceResponse]) error {
	return status.Error(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedMessageProxyServer) Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedMessageProxyServer) mustEmbedUnimplementedMessageProxyServer() {}
func (UnimplementedMessageProxyServer) testEmbeddedByValue()                      {}

// UnsafeMessageProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageProxyServer will
// result in compilation errors.
type UnsafeMessageProxyServer interface {
	mustEmbedUnimplementedMessageProxyServer()
}

func RegisterMessageProxyServer(s grpc.ServiceRegistrar, srv MessageProxyServer) {
	// If the following call panics, it indicates UnimplementedMessageProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageProxy_ServiceDesc, srv)
}

func _MessageProxy_Produce_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageProxyServer).Produce(&grpc.GenericServerStream[ProduceRequest, ProduceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageProxy_ProduceServer = grpc.BidiStreamingServer[ProduceRequest, ProduceResponse]

func _MessageProxy_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageProxyServer).Consume(&grpc.GenericServerStream[ConsumeRequest, ConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageProxy_ConsumeServer = grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]

// MessageProxy_ServiceDesc is the grpc.ServiceDesc for MessageProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_proxy.MessageProxy",
	HandlerType: (*MessageProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Produce",
			Handler:       _MessageProxy_Produce_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _MessageProxy_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/message_proxy.proto",
}
